# Generated by Django 3.0.3 on 2020-02-22 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200221_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('spotify_email', models.CharField(max_length=100)),
                ('spotify_name', models.CharField(max_length=100)),
                ('spotify_id', models.CharField(max_length=25)),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
    ]
